# Generated by Django 5.1.4 on 2025-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('priority', models.IntegerField()),
                ('category', models.CharField(max_length=100)),
                ('assigned_to', models.ManyToManyField(related_name='assigned_tasks', to='user_auth_app.userprofile')),
            ],
        ),
    ]
