# Generated by Django 5.1.4 on 2025-02-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_remove_customuser_emblem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='color',
            new_name='contactColor',
        ),
    ]
