# Generated by Django 5.1.4 on 2025-02-10 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0003_rename_color_customuser_contactcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Enter a valid username. Only letters, numbers, spaces, and @/./+/-/_ are allowed.', regex='^[\\w.@+\\- ]+$')]),
        ),
    ]
