# Generated by Django 5.1.4 on 2025-02-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0004_alter_customuser_phone_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
