# Generated by Django 5.1.4 on 2025-01-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0002_remove_task_user_task_users'),
        ('user_auth_app', '0003_userprofile_contactcolor_userprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='users',
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='user_auth_app.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='general', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='task',
            name='users_assigned_to',
            field=models.ManyToManyField(to='user_auth_app.userprofile'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
