# Generated by Django 5.1.4 on 2025-01-21 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0003_remove_contact_user_contact_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='color',
            new_name='contactColor',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
