# Generated by Django 5.1.4 on 2025-01-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='contactColor',
            field=models.CharField(default='#FF7A00', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='initials',
            field=models.CharField(default='MM', max_length=5),
        ),
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.CharField(default='Max@Musteremail.de', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='Max Mustermann', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='012345678', max_length=100),
        ),
    ]
