# Generated by Django 5.1.4 on 2025-01-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0004_rename_color_contact_contactcolor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='users',
        ),
        migrations.AddField(
            model_name='contact',
            name='conatct_is_a_user',
            field=models.BooleanField(default=True),
        ),
    ]
