# Generated by Django 5.1.4 on 2025-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0006_rename_conatct_is_a_user_contact_contact_is_a_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='contact',
            name='mail',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
