# Generated by Django 5.1.4 on 2025-01-24 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0007_remove_contact_additional_info_contact_mail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
