# Generated by Django 5.1.4 on 2025-01-29 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0009_contact_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('category-1', 'Category 1'), ('category-2', 'Category 2'), ('category-3', 'Category 3')], default='category-1', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('technical_task', 'Technical Task'), ('management_task', 'Management Task'), ('design_task', 'Design Task')], max_length=20, null=True),
        ),
    ]
