# Generated by Django 5.1.4 on 2025-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0010_task_assigned_to_task_category_task_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(blank=True, choices=[('technical_task', 'Technical Task'), ('management_task', 'Management Task'), ('design_task', 'Design Task'), ('user_story', 'User Story')], max_length=20, null=True),
        ),
    ]
