# Generated by Django 5.1.4 on 2025-01-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0011_alter_task_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('category-0', 'Category 0'), ('category-1', 'Category 1'), ('category-2', 'Category 2'), ('category-3', 'Category 3')], default='category-1', max_length=50),
        ),
    ]
