# Generated by Django 5.1.4 on 2025-02-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0012_alter_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='assigned_tasks', to='join_backend_app.contact'),
        ),
    ]
