# Generated by Django 5.1.4 on 2025-02-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0013_alter_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to='join_backend_app.contact'),
        ),
    ]
