# Generated by Django 5.1.4 on 2025-02-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0014_contact_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='assigned_to',
        ),
    ]
