# Generated by Django 5.1.4 on 2025-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0015_remove_contact_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
