# Generated by Django 5.1.4 on 2025-02-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0016_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
