# Generated by Django 5.1.4 on 2025-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_backend_app', '0018_task_subtasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
